### ISSUE TITLE
&PriveHD channel not able to play

### ISSUE THREAD

**Issue by jiomvk** [Oshekher/Zee5-LiveTV-Scrapper#2]
&PriveHD channel not able to play

Format used: https://zee.puritynothere.repl.co/?c=0-9-priv%C3%A9hd

Getting error: {"error":"Something went wrong, Check URL","Repo":"https:\/\/github.com\/Oshekher\/Zee5-LiveTV-Scrapper"}

Kindly look in to this issue,

**Comment by Oshekher** [comment]
I will check this later till that try this: 

https://tv.zee5play.ml/c/0-9-priv%C3%A9hd

• Put Complete I'd : https://tv.zee5play.ml/z/CHANNEL_ID | ( Player Added )

• Put I'd after 0-9- : https://tv.zee5play.ml/c/CHANNEL_ID | (Player Added )

• Put I'd after 0-9- : https://tv.zee5play.ml/x/CHANNEL_ID | ( For Play in other Players or IPTV )

**Comment by jiomvk** [comment]
Checked all the options above, it looks like the issue with font of the channel name as it uses : 0-9-privéhd special characters which we need to find, 

same time the channels works on zee5 website
